-- This module is the root of the TateShafarevichFinitenessCanonicalLaneLean Lean proof package.
import TateShafarevichFinitenessCanonicalLaneLean.Basic
import TateShafarevichFinitenessCanonicalLaneLean.SourcePackage
import TateShafarevichFinitenessCanonicalLaneLean.SourceDependencies
import TateShafarevichFinitenessCanonicalLaneLean.Formalization
import TateShafarevichFinitenessCanonicalLaneLean.ReviewerBridge
import TateShafarevichFinitenessCanonicalLaneLean.TheoremStatement
import TateShafarevichFinitenessCanonicalLaneLean.MathlibObjects
import TateShafarevichFinitenessCanonicalLaneLean.AdmissibleClass
import TateShafarevichFinitenessCanonicalLaneLean.Projection
import TateShafarevichFinitenessCanonicalLaneLean.BridgeLemmas
import TateShafarevichFinitenessCanonicalLaneLean.GateLemmas
import TateShafarevichFinitenessCanonicalLaneLean.FinalTheorem
import TateShafarevichFinitenessCanonicalLaneLean.MathlibStatement
